name: Deploy

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

env:
  BRANCH_NAME: ${{ github.event_name == 'pull_request' && github.head_ref || 'main' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Set url
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build project
        run: npm run build
      - name: Run deploychik
        run: |
          npx gh-pages \
          --remove ./${{ env.BRANCH_NAME }} \
          --branch build \
          --dist ./dist \
          --dest ./${{ env.BRANCH_NAME }} \
          --user "olek <oleg@gmail.kek>"
      - name: Send comment to pull request
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            :rocket: Деплой данной ветки можно посмотреть [здесь](${{ 'https://github.com/okovtkov/sites-builder' }})
          comment_tag: execution
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  remove-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Remove folder from sorybook branch
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git config --global user.email "olek"
          git config --global user.name "oleg@gmail.kek"
          git fetch origin build
          git checkout build
          git rm -r ${{ github.head_ref }}
          git commit -a -n -m "remove ${{ github.head_ref }}"
          git push origin build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
